#!/bin/bash
if [ "$(id -u)" != "0" ]; then
    mkdir yoda
    cd yoda
    printf "FROM kcmerrill/yoda\n\nRUN useradd $(whoami) -u $(id -u $USER)" > Dockerfile
    docker build -t yodabin .
    printf "To finalize your yoda installation, simply put this into your ~/.bash_profile as an alias\n\n\nalias";
    printf 'alias yoda='\''docker run --rm -ti --name yodaapp -v $HOME/.ssh:$HOME/.ssh -v $HOME/.yoda/shares:/yoda/www/share -v $HOME/.docker:$HOME/.docker -v $HOME/.yoda:$HOME/.yoda -e containerized=true -h=$HOSTNAME -v /var/run/docker.sock:/var/run/docker.sock -v $(if [ $(dirname $PWD) == "/" ]; then echo $PWD; else dirname $PWD; fi):$(if [ $(dirname $PWD) == "/" ]; then echo $PWD; else dirname $PWD; fi) -w $PWD -u $(id -u $USER) yodabin'\'')';
    exit 0
fi

printf "To finalize your yoda installation, simply put this into your ~/.bash_profile as an alias\n\n";
printf 'alias yoda='\''docker run --rm -ti --name yodaapp -v $HOME/.ssh:$HOME/.ssh -v $HOME/.yoda/shares:/yoda/www/share -v $HOME/.docker:$HOME/.docker -v $HOME/.yoda:$HOME/.yoda -e containerized=true -h=$HOSTNAME -v /var/run/docker.sock:/var/run/docker.sock -v $(if [ $(dirname $PWD) == "/" ]; then echo $PWD; else dirname $PWD; fi):$(if [ $(dirname $PWD) == "/" ]; then echo $PWD; else dirname $PWD; fi) -w $PWD -u $(id -u $USER) kcmerrill/yoda'\''';
